### ISSUE TITLE
Show Exif informations (lack)

### ISSUE THREAD

**Issue by n40l-remimu** [cpg-contrib/coppermine#2]
Hello,
I'm using cpg1.5.38 and I see date added but not the Exif information of images.
This is mainly the date and time\* of shooting might appear naturally.
this is not an issue strictly speaking; I am a beginner on this interface.
Thanks
ps: I've upgrade to 1.6.x from Git and it does not change this request.
- and place, device information

**Comment by remimu** [comment]
I made a mistake :
The EXIF (with Administration) and IPTC jpeg files are avalaible in Configuration / Files Parameters

**Comment by n40l-remimu** [comment]
I made a mistake :
The EXIF (with Administration) and IPTC jpeg files informations are avalaible in Configuration / Files Parameters
